## RAGAS Evaluation of the Chatbot component of FIONAA.


Create separate SGDs on for  company

calc the metrics


create a hybrid retriever with lexical search to compare

In [14]:

from operator import itemgetter

import nest_asyncio
from dotenv import load_dotenv
from langchain_classic.retrievers.ensemble import EnsembleRetriever
from langchain_community.retrievers import BM25Retriever
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_docling.loader import DoclingLoader

#Semantic search scoped to a single case
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.llms import LangchainLLMWrapper
from ragas.testset import TestsetGenerator

nest_asyncio.apply()  

load_dotenv()

True

In [77]:

loader = DoclingLoader(file_path="../data/synthesia/synthesia_companies_house_document.pdf")
raw_docs = loader.load()

2026-02-28 19:32:08,266 - INFO - detected formats: [<InputFormat.PDF: 'pdf'>]
2026-02-28 19:32:08,317 - INFO - Going to convert document batch...
2026-02-28 19:32:08,318 - INFO - Initializing pipeline for StandardPdfPipeline with options hash e15bc6f248154cc62f8db15ef18a8ab7
2026-02-28 19:32:08,323 - INFO - Auto OCR model selected ocrmac.
2026-02-28 19:32:08,327 - INFO - Accelerator device: 'mps'
2026-02-28 19:32:12,346 - INFO - Accelerator device: 'mps'
2026-02-28 19:32:13,038 - INFO - Processing document synthesia_companies_house_document.pdf
2026-02-28 19:32:54,159 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-21854' coro=<as_completed.<locals>.sema_coro() done, defined at /Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/ragas/async_utils.py:75> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3701, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/bz/qcwzc_9j6zgggtsc_fbjryy40000gp/T/ipykernel_97276/2027606331.py", line 11, in <module>
    currys_dataset = generator.generate_with_langchain_docs(raw_docs, testset_size=20, query_distribution=query_distribution)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/ragas/testset/synthesizers/generate.py", line 208, in generate_with_langchain_docs
    apply_transforms(kg, transforms, run_config=run_config or RunConfig())
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/ragas/testset/transforms/engine.py", line 70, in apply_transforms
    apply_transforms(kg, transform, run_config, callbacks)
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/ragas/testset/transforms/engine.py", line 79, in apply_transforms
    run_async_tasks(
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/ragas/async_utils.py", line 232, in run_async_tasks
    return run(_run)
           ^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/ragas/async_utils.py", line 156, in run
    return asyncio.run(coro)
           ^^^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/nest_asyncio.py", line 92, in run_until_complete
    self._run_once()
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/nest_asyncio.py", line 133, in _run_once
    handle._run()
  File "/Users/stevegoodman/.local/share/uv/python/cpython-3.12.10-macos-aarch64-none/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/stevegoodman/.local/share/uv/python/cpython-3.12.10-macos-aarch64-none/lib/python3.12/asyncio/tasks.py", line 396, in __wakeup
    self.__step()
  File "/Users/stevegoodman/.local/share/uv/python/cpython-3.12.10-macos-aarch64-none/lib/python3.12/asyncio/tasks.py", line 303, in __step
    self.__step_run_and_handle_result(exc)
  File "/Users/stevegoodman/.local/share/uv/python/cpython-3.12.10-macos-aarch64-none/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/ragas/async_utils.py", line 77, in sema_coro
    return await coro
           ^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/ragas/testset/transforms/base.py", line 420, in apply_filter
    if await self.custom_filter(node, kg):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/ragas/testset/transforms/filters.py", line 85, in custom_filter
    response = await self.scoring_prompt.generate(data=prompt_input, llm=self.llm)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/ragas/prompt/pydantic_prompt.py", line 177, in generate
    output_single = await self.generate_multiple(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/ragas/prompt/pydantic_prompt.py", line 339, in generate_multiple
    track(
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/ragas/_analytics.py", line 63, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/ragas/_analytics.py", line 233, in track
    requests.post(USAGE_TRACKING_URL, json=payload, timeout=USAGE_REQUESTS_TIMEOUT_SEC)
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/requests/adapters.py", line 644, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 404, in _make_request
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1061, in _validate_conn
    actual_host: str = self.host
        ^^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 419, in connect
    f"urllib3.util.SKIP_HEADER only supports '{skippable_headers}'"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 458, in ssl_wrap_socket
  File "/Users/stevegoodman/dev/fionaa-be/.venv/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 502, in _ssl_wrap_socket_impl
    with open(key_file) as f:
               ^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/.local/share/uv/python/cpython-3.12.10-macos-aarch64-none/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevegoodman/.local/share/uv/python/cpython-3.12.10-macos-aarch64-none/lib/python3.12/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/Users/stevegoodman/.local/share/uv/python/cpython-3.12.10-macos-aarch64-none/lib/python3.12/ssl.py", line 1319, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt
2026-02-28 19:33:31,570 - INFO - Finished converting document synthesia_companies_house_document.pdf in 83.33 sec.
Token indices sequence length is longer than the specified maximum sequence length for this model (520 > 512). Running this sequence through the model will result in indexing errors

In [78]:
generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings())

/var/folders/bz/qcwzc_9j6zgggtsc_fbjryy40000gp/T/ipykernel_97276/507413754.py:1: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
/var/folders/bz/qcwzc_9j6zgggtsc_fbjryy40000gp/T/ipykernel_97276/507413754.py:2: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings())

In [ ]:

generator = TestsetGenerator(llm=generator_llm, embedding_model=generator_embeddings)
from ragas.testset.synthesizers import (
  SingleHopSpecificQuerySynthesizer,
)

query_distribution = [
    (SingleHopSpecificQuerySynthesizer(llm=generator_llm), 1.0),
]
dataset = generator.generate_with_langchain_docs(raw_docs, testset_size=20, query_distribution=query_distribution)

In [23]:
dataset.to_pandas()

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name
0,What this 10933652 mean in the annual report a...,[ANNUAL REPORT AND FINANCIAL STATEMENTS FOR TH...,10933652 is the registered number shown in the...,Financial Analyst,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer
1,When was Philip Karim Chopin appointed as a di...,[COMPANY INFORMATION\nDirectors\nSteffen Tjerr...,Philip Karim Chopin was appointed as a directo...,IFRS Compliance Accountant,PERFECT_GRAMMAR,MEDIUM,single_hop_specific_query_synthesizer
2,wher is Consolidated Statement of Changes in E...,"[CONTENTS\nGroup Strategic Report, Page = 1-2....",The Consolidated Statement of Changes in Equit...,Financial Analyst,MISSPELLED,SHORT,single_hop_specific_query_synthesizer
3,What is the significance of 31 December 2024 i...,[Introduction\nThe Directors present their str...,31 December 2024 marks the end of the financia...,IFRS Compliance Accountant,PERFECT_GRAMMAR,MEDIUM,single_hop_specific_query_synthesizer
4,"What were the Group's consolidated revenue, lo...",[Business review\nThe Group's principal activi...,"For the year ended 31 December 2023, the Group...",Financial Analyst,WEB_SEARCH_LIKE,MEDIUM,single_hop_specific_query_synthesizer
5,wat does the board do?,[Financial key performance indicators\nAnnual ...,The board agrees annual budgets in advance and...,Financial Compliance Officer,MISSPELLED,SHORT,single_hop_specific_query_synthesizer
6,"In the context of IFRS 15 compliance, how does...",[Principal risks and uncertainties\nThe key bu...,The term Group refers to the collective entity...,IFRS Compliance Accountant,PERFECT_GRAMMAR,LONG,single_hop_specific_query_synthesizer
7,How come the company gotta rely so much on thi...,[Hosting risk\nThe Group is primarily dependen...,The company is mainly dependent on third party...,Financial Analyst,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer
8,How The Group gonna get hurt if they not get n...,[Customer relations and competition risk\nThe ...,The Group's future revenues and operating resu...,Financial Analyst,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer
9,Did any single customer account for more than ...,[Liquidity risk\nThe Group currently is cash f...,No single customer accounted for more than 10%...,Financial Compliance Officer,PERFECT_GRAMMAR,MEDIUM,single_hop_specific_query_synthesizer
10,How does the GROUP address currency risk accor...,[GROUP STRATEGIC REPORT (CONTINUED) FOR THE YE...,The GROUP addresses currency risk by attemptin...,IFRS Compliance Accountant,PERFECT_GRAMMAR,MEDIUM,single_hop_specific_query_synthesizer
11,Howw does teh Group use Net Dolllar Retention ...,[Other key performance indicators\nOther key p...,Net Dollar Retention is listed as one of the k...,IFRS Compliance Accountant,MISSPELLED,LONG,single_hop_specific_query_synthesizer
12,What does the Companies Act 2006 require direc...,[Directors' statement of compliance with duty ...,Under Section 172(1) of the Companies Act 2006...,Financial Compliance Officer,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer
13,Who is Steffen Tjerrild-Hansen and what is his...,[Directors' statement of compliance with duty ...,Steffen Tjerrild-Hansen is listed as a Directo...,IFRS Compliance Accountant,MISSPELLED,LONG,single_hop_specific_query_synthesizer
14,What is the significance of 31 December 2024 i...,[DIRECTORS' REPORT FOR THE YEAR ENDED 31 DECEM...,31 December 2024 marks the end of the financia...,Financial Compliance Officer,WEB_SEARCH_LIKE,MEDIUM,single_hop_specific_query_synthesizer
15,wht is the grup doin as main activty?,[Principal activity\nThe Group's principal act...,The Group's principal activity is the developm...,IFRS Compliance Accountant,MISSPELLED,MEDIUM,single_hop_specific_query_synthesizer
16,wht ws the loss in 2023?,"[Results and dividends\nThe loss for the year,...","The loss in 2023 amounted to $26,140,759.",Financial Analyst,MISSPELLED,SHORT,single_hop_specific_query_synthesizer
17,Wen is the grup expectin to see groth in custm...,[Future developments\nThe directors believe th...,The Group anticipates growth in customers and ...,Financial Compliance Officer,MISSPELLED,LONG,single_hop_specific_query_synthesizer
18,What happened with the Series D-1 Preferred Sh...,[Events after the reporting period\nThe follow...,"After the reporting date, the Group raised an ...",IFRS Compliance Accountant,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer
19,What information does Streamlined Energy and C...,[Streamlined Energy and Carbon Reporting (SECR...,Streamlined Energy and Carbon Reporting provid...,Financial Analyst,WEB_SEARCH_LIKE,MEDIUM,single_hop_specific_query_synthesizer

In [25]:
dataset.to_pandas().to_csv('synthesia_sdg.csv')

In [4]:
# Construct rag app
from vector_store import get_store

In [70]:

RAG_TEMPLATE = """\
You are a financial assistant. Use the context provided below to answer the question.

If you do not know the answer, or are unsure, say you don't know.
Be concise and specific.

Query:
{question}

Context:
{context}
"""

rag_prompt = ChatPromptTemplate.from_template(RAG_TEMPLATE)

chat_model = ChatOpenAI(model="gpt-4.1-nano")
store = await get_store()
case_number="SteveGoodman"
retriever = store.as_retriever(
    search_kwargs={
        "filter": {"case_number": case_number},
        "k": 5
    }
)

In [63]:
naive_retrieval_chain = (
    {"context": itemgetter("question") | retriever, "question": itemgetter("question")}
    # "context"  : is assigned to a RunnablePassthrough object (will not be called or considered in the next step)
    #              by getting the value of the "context" key from the previous step
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

result = await naive_retrieval_chain.ainvoke({"question" : "what are the key risks seen by this company?"})
result["response"].content

2026-02-28 18:05:50,307 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-9975-7eb1-944a-e4d933cc5a35; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-9981-7f13-a5f5-c4dbdaacf1d7; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-9982-7bf1-9667-a738617394a1; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-9983-7c60-aa41-84c515d20b74; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-9984-7de0-9fce-87ac143e42af; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-9983-7c60-aa41-84c515d20b74; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-9984-7de0-9fce-87ac143e42af; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-9a31-7200-b8e6-062186e090de
2026-02-28 18:05:52,007 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 18:05:52,759 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-9a31-7200-b8e6-062186e090de; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-9982-7bf1-9667-a738617394a1; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-9981-7f13-a5f5-c4dbdaacf1d7; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a45c-7ae0-b255-f1370db03be5; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a45c-7ae0-b255-f14273a70390; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a45d-79e0-99e4-4b27c255f065; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a45d-79e0-99e4-4b27c255f065; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a45c-7ae0-b255-f14273a70390; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a45c-7ae0-b255-f1370db03be5; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a45e-7563-8070-59f96907eece; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a45e-7563-8070-5a0b62e1c29b; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a45f-7fe0-a3ec-60210b8b40be; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a45f-7fe0-a3ec-60354e62e6eb; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a45f-7fe0-a3ec-60354e62e6eb; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a45f-7fe0-a3ec-60210b8b40be; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a469-7d22-8bce-f60ee419de21
2026-02-28 18:05:54,584 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

'Based on the provided documents, the key risks seen by the company are not explicitly detailed. However, some potential risks can be inferred:\n\n1. **Limited audit requirements** - The company has not been required to obtain an audit due to its small company status, which might pose risks related to the completeness and accuracy of financial reporting.\n\n2. **Control and Ownership Concentration** - The company is controlled entirely by the director who owns 100% of the share capital, which could pose risks related to governance, lack of checks and balances, and potential for mismanagement or conflicts of interest.\n\n3. **Financial Performance** - The company has shown a slight increase in turnover from £99,163 to £101,112, but also face relatively low profit margins with significant administrative and employment expenses, which might impact profitability and financial stability.\n\n4. **Dependence on a Single Control Person** - Since all control resides with one individual, there is inherent risk if that individual were to become unavailable or make poor decisions.\n\nPlease note that these are inferences based on the available information, and the documents do not explicitly outline specific risks as they might in a formal risk section.'

2026-02-28 18:05:55,307 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a469-7d22-8bce-f60ee419de21; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a45e-7563-8070-5a0b62e1c29b; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-a45e-7563-8070-59f96907eece; trace=019ca56d-9975-7eb1-944a-e4d933cc5a35,id=019ca56d-9975-7eb1-944a-e4d933cc5a35

In [87]:
case_number="Synthesia"


retriever = store.as_retriever(
    search_kwargs={
        "filter": {"case_number": case_number},
        "k": 5
    }
)

naive_retrieval_chain = (
    {"context": itemgetter("question") | retriever, "question": itemgetter("question")}
    # "context"  : is assigned to a RunnablePassthrough object (will not be called or considered in the next step)
    #              by getting the value of the "context" key from the previous step
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

result = await naive_retrieval_chain.ainvoke({"question" : "what are the key risks seen by this company?"})
result["response"].content

2026-02-28 19:45:29,894 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-d799-7770-b1b9-2264e5a4fd41; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-d7a7-7a22-ba87-82f008ca1413; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-d7a8-7c60-8b84-9f25c2376500; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-d7a9-76c2-a7ed-666ac486a0b2; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-d7a9-76c2-a7ed-6679c5b954a6; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-d7a9-76c2-a7ed-666ac486a0b2; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-d7a9-76c2-a7ed-6679c5b954a6; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-d7c3-7573-be7e-aea27326756b
2026-02-28 19:45:32,383 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 19:45:33,241 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-d7c3-7573-be7e-aea27326756b; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-d7a8-7c60-8b84-9f25c2376500; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-d7a7-7a22-ba87-82f008ca1413; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e590-7382-8454-48e2bb1598ca; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e590-7382-8454-48fee1c676b8; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e590-7382-8454-49020a384819; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e590-7382-8454-49020a384819; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e590-7382-8454-48fee1c676b8; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e590-7382-8454-48e2bb1598ca; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e595-7c20-a8ac-c497d78bbb3e; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e595-7c20-a8ac-c4a93dd5742a; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e595-7c20-a8ac-c4b28d5a985b; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e598-7871-9d48-d3db3c9c93e9; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e598-7871-9d48-d3db3c9c93e9; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e595-7c20-a8ac-c4b28d5a985b; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e59e-7bf3-ab37-0158d103c28c
2026-02-28 19:45:34,104 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

'The key risks include customer relation and competition risks, financial risks such as credit and liquidity risks, and the reliance on external capital due to current cash flow negativity.'

2026-02-28 19:45:34,780 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e59e-7bf3-ab37-0158d103c28c; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e595-7c20-a8ac-c4a93dd5742a; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-e595-7c20-a8ac-c497d78bbb3e; trace=019ca5c8-d799-7770-b1b9-2264e5a4fd41,id=019ca5c8-d799-7770-b1b9-2264e5a4fd41

In [33]:
from ragas import EvaluationDataset, RunConfig, evaluate
from ragas.metrics import (
  ContextEntityRecall,
  ContextPrecision,
  FactualCorrectness,
  Faithfulness,
  LLMContextRecall,
)

custom_run_config = RunConfig(timeout=360)
evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1-mini"))


async def aevaluate_retreiver(candidate_retreiver, retriever_name):
  for test_row in dataset:
    response = await candidate_retreiver.ainvoke({"question" : test_row.eval_sample.user_input})
    test_row.eval_sample.response = response["response"].content
    test_row.eval_sample.retrieved_contexts = [context.page_content for context in response["context"]]

  evaluation_dataset = EvaluationDataset.from_pandas(dataset.to_pandas())

  result = evaluate(
      dataset=evaluation_dataset,
      metrics=[ContextPrecision(), LLMContextRecall(), Faithfulness(), FactualCorrectness(),  ContextEntityRecall()],
      llm=evaluator_llm,
      run_config=custom_run_config
  )
  return result 

baseline_synthesia_result = await aevaluate_retreiver(naive_retrieval_chain, 'naive_retriever')

baseline_synthesia_result

/var/folders/bz/qcwzc_9j6zgggtsc_fbjryy40000gp/T/ipykernel_97276/1263718308.py:1: DeprecationWarning: Importing ContextPrecision from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ContextPrecision
  from ragas.metrics import ContextPrecision, LLMContextRecall, Faithfulness, FactualCorrectness, ContextEntityRecall
/var/folders/bz/qcwzc_9j6zgggtsc_fbjryy40000gp/T/ipykernel_97276/1263718308.py:1: DeprecationWarning: Importing LLMContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextRecall
  from ragas.metrics import ContextPrecision, LLMContextRecall, Faithfulness, FactualCorrectness, ContextEntityRecall
/var/folders/bz/qcwzc_9j6zgggtsc_fbjryy40000gp/T/ipykernel_97276/1263718308.py:1: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import ContextPrecision, LLMContextRecall, Faithfulness, FactualCorrectness, ContextEntityRecall
/var/folders/bz/qcwzc_9j6zgggtsc_fbjryy40000gp/T/ipykernel_97276/1263718308.py:1: DeprecationWarning: Importing FactualCorrectness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import FactualCorrectness
  from ragas.metrics import ContextPrecision, LLMContextRecall, Faithfulness, FactualCorrectness, ContextEntityRecall
/var/folders/bz/qcwzc_9j6zgggtsc_fbjryy40000gp/T/ipykernel_97276/1263718308.py:1: DeprecationWarning: Importing ContextEntityRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ContextEntityRecall
  from ragas.metrics import ContextPrecision, LLMContextRecall, Faithfulness, FactualCorrectness, ContextEntityRecall
/var/folders/bz/qcwzc_9j6zgggtsc_fbjryy40000gp/T/ipykernel_97276/1263718308.py:5: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1-mini"))
2026-02-28 15:41:35,845 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:41:37,313 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:41:37,530 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:41:38,439 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:41:38,720 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:41:39,471 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:41:39,712 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:41:41,075 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:41:41,813 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:41:42,923 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:41:43,123 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:41:44,454 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:41:44,646 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:41:47,815 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:41:47,950 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:41:50,332 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:41:50,457 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:41:51,528 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:41:51,686 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:41:52,584 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:41:52,713 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:41:53,869 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:41:54,188 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:41:56,077 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:41:56,230 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
/Users/stevegoodman/.local/share/uv/python/cpython-3.12.10-macos-aarch64-none/lib/python3.12/selectors.py:192: RuntimeWarning: coroutine 'AsyncPGVectorStore.asimilarity_search' was never awaited
  raise KeyError("{!r} is not registered".format(fileobj)) from None
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2026-02-28 15:41:58,146 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:41:58,381 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:42:00,093 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:00,216 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:42:01,248 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:01,452 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:42:02,122 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:02,291 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:42:03,061 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:03,229 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:42:04,507 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:04,977 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:42:06,233 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:06,675 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 15:42:10,124 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Evaluating:   0%|          | 0/100 [00:00<?, ?it/s]

2026-02-28 15:42:11,487 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:11,488 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:11,489 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:13,068 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:13,069 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:13,070 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:13,071 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:13,072 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:13,073 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:13,078 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:13,079 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:13,079 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:13,080 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:13,080 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:13,081 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:13,082 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:13,083 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:20,050 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:20,054 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:20,055 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:21,087 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:22,153 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:22,659 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:23,164 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:23,165 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:23,166 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:24,676 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:24,677 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:24,680 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:24,681 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:24,683 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:24,684 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:24,692 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:24,694 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:28,293 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:28,295 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:28,301 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:28,302 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:28,303 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:28,307 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:28,308 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:28,310 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:28,804 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:32,805 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:33,300 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:33,302 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:33,303 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:33,304 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:35,793 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:35,796 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:35,797 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:35,798 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:37,814 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:37,816 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:38,910 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:39,437 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:39,965 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:39,967 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:39,968 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:41,465 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:41,466 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:41,468 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:41,469 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:41,469 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:41,470 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:41,476 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:41,477 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:45,461 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:45,462 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:45,463 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:45,465 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:45,466 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:45,467 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:45,476 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:45,477 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:48,974 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:48,975 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:48,975 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:50,980 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:50,983 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:50,985 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:52,492 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:52,495 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:52,501 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:53,992 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:53,994 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:53,995 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:55,570 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:55,572 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:55,573 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:55,574 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:55,584 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:57,613 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:57,613 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:57,614 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:57,615 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:57,616 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:57,617 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:42:57,617 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:01,576 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:01,577 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:01,585 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:01,587 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:01,588 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:03,082 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:04,115 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:04,121 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:05,100 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:05,592 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:06,611 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:06,612 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:06,613 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:06,614 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:06,619 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:09,095 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:09,096 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:09,096 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:09,099 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:09,100 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:09,101 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:12,115 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:12,117 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:12,119 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:12,127 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:14,111 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:14,117 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:14,119 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:15,097 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:15,098 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:15,576 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:15,577 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:16,536 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:16,537 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:17,512 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:17,514 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:17,516 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:18,482 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:18,483 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:19,930 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:19,931 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:19,932 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:19,934 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:19,936 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:23,386 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:23,389 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:24,805 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:25,292 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:25,294 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:25,295 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:26,816 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:26,819 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:26,820 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:26,822 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:26,823 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:26,823 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:26,824 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:30,255 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:30,257 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:30,258 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:30,263 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:30,265 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:30,265 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:30,266 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:30,267 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:30,268 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:34,760 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:34,763 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:34,783 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:35,778 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:36,300 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:36,300 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:37,287 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:37,782 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:37,785 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:38,766 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 15:43:39,358 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

{'context_precision': 0.7167, 'context_recall': 0.8750, 'faithfulness': 0.7461, 'factual_correctness(mode=f1)': 0.5055, 'context_entity_recall': 0.5713}

In [89]:
# Hybrid retriever: BM25 (sparse) + pgvector dense search combined via EnsembleRetriever
# BM25Retriever operates on an in-memory document list, so we first fetch all chunks
# for the case from pgvector, then hand them to BM25.


case_number = "Synthesia"

# --- 1. Fetch all documents for this case to seed BM25 ---
# We use a broad similarity search with a high k; for production you'd page through
# all rows, but for evaluation this is sufficient.
all_docs = await store.asimilarity_search(
    "company overview",
    k=200,
    filter={"case_number": case_number},
)
print(f"Fetched {len(all_docs)} docs for BM25 corpus")

# --- 2. Sparse retriever (BM25) ---
bm25_retriever = BM25Retriever.from_documents(all_docs, k=5)

# --- 3. Dense retriever (pgvector cosine similarity) ---
dense_retriever = store.as_retriever(
    search_kwargs={"filter": {"case_number": case_number}, "k": 5}
)

# --- 4. Ensemble: equal weights, deduplication via Reciprocal Rank Fusion ---
hybrid_retriever = EnsembleRetriever(
    retrievers=[bm25_retriever, dense_retriever],
    weights=[0.5, 0.5],
)

# Smoke test
test_docs = await hybrid_retriever.ainvoke("what are the key risks seen by this company?")
print(f"Hybrid retriever returned {len(test_docs)} docs")
for d in test_docs[:2]:
    print(f"  [{d.metadata.get('chunk_type', '?')} p{d.metadata.get('page_num', '?')}] {d.page_content[:120]}...")

2026-02-28 19:51:53,132 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

Fetched 200 docs for BM25 corpus

2026-02-28 19:51:53,952 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca5ce-b493-7dd1-b14b-f5456e1fd3ac,id=019ca5ce-b493-7dd1-b14b-f5456e1fd3ac; trace=019ca5ce-b493-7dd1-b14b-f5456e1fd3ac,id=019ca5ce-b495-7530-af4a-8a8f1524c9bf; trace=019ca5ce-b493-7dd1-b14b-f5456e1fd3ac,id=019ca5ce-b496-77e2-bd1e-b5940f3d104d; trace=019ca5ce-b493-7dd1-b14b-f5456e1fd3ac,id=019ca5ce-b495-7530-af4a-8a8f1524c9bf
2026-02-28 19:51:55,643 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

Hybrid retriever returned 9 docs
  [chunkText p3] <a id='ad1fddc4-f074-40cc-8e5b-f1cb14cd1011'></a>

**Principal risks and uncertainties**
The key business risks that cou...
  [chunkText p9] <a id='832ddbc3-b718-46d0-88af-d2b338435ffc'></a>

Our responsibilities and the responsibilities of the directors with r...

2026-02-28 19:51:56,360 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca5ce-b493-7dd1-b14b-f5456e1fd3ac,id=019ca5ce-b496-77e2-bd1e-b5940f3d104d; trace=019ca5ce-b493-7dd1-b14b-f5456e1fd3ac,id=019ca5ce-b493-7dd1-b14b-f5456e1fd3ac

In [90]:
# Wrap hybrid_retriever in the same RAG chain shape used by aevaluate_retreiver
hybrid_retrieval_chain = (
    {"context": itemgetter("question") | hybrid_retriever, "question": itemgetter("question")}
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

hybrid_synthesia_result = await aevaluate_retreiver(hybrid_retrieval_chain, "hybrid_retriever")
hybrid_synthesia_result

2026-02-28 19:52:09,077 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 19:52:09,924 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f17c-7d62-bb88-74d6eab3d86c; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f17e-7493-b880-b838dab02edf; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f17f-7f73-9747-7424a3916836; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f180-7d73-98d0-363186027aec; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f181-74f2-ad10-da1a6b35319c; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f181-74f2-ad10-da1a6b35319c; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f180-7d73-98d0-363186027aec; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f1a3-7672-8194-47fa90788ad2; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f1a4-7df3-8eaf-bdf2e25965a8; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f1a4-7df3-8eaf-be04e9599a7e; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f1a4-7df3-8eaf-bdf2e25965a8; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f1a4-7df3-8eaf-be04e9599a7e; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f1a3-7672-8194-47fa90788ad2; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f17f-7f73-9747-7424a3916836; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f17e-7493-b880-b838dab02edf; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2d5-7232-99fe-5524684ad3aa; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2d6-7a13-921d-d93da08f540d; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2d7-7060-9c76-2fda89cce088; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2d7-7060-9c76-2fda89cce088; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2d6-7a13-921d-d93da08f540d; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2d5-7232-99fe-5524684ad3aa; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2e0-7b81-8adb-61e35eb17a5a; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2e0-7b81-8adb-61fc5c13a793; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2e1-7353-9df5-ae5e104f0c51; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2e1-7353-9df5-ae6e88ca9c90; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2e1-7353-9df5-ae6e88ca9c90; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2e1-7353-9df5-ae5e104f0c51; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2e4-7a93-ac43-3b1d26d807b8
2026-02-28 19:52:11,157 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:11,302 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 19:52:11,995 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2e4-7a93-ac43-3b1d26d807b8; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2e0-7b81-8adb-61fc5c13a793; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f2e0-7b81-8adb-61e35eb17a5a; trace=019ca5ce-f17c-7d62-bb88-74d6eab3d86c,id=019ca5ce-f17c-7d62-bb88-74d6eab3d86c; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa1-7c21-ad56-19ec151e6ee2; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa2-7b52-8897-0e5436078375; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa2-7b52-8897-0e67cf3655c6; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa3-7d21-bad4-85dd5c2f60a8; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa3-7d21-bad4-85e032339b43; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa3-7d21-bad4-85dd5c2f60a8; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa3-7d21-bad4-85e032339b43; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa6-7d70-8522-97f79641c113; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa7-7422-a3de-e15bab893da5; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa7-7422-a3de-e16cf115a358; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa7-7422-a3de-e15bab893da5; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa7-7422-a3de-e16cf115a358; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa6-7d70-8522-97f79641c113; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa2-7b52-8897-0e67cf3655c6; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa2-7b52-8897-0e5436078375; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb3e-7571-a48d-0394044ed633; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb3f-7893-a979-601378938601; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb3f-7893-a979-6028b0f4db79; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb3f-7893-a979-6028b0f4db79; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb3f-7893-a979-601378938601; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb3e-7571-a48d-0394044ed633; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb43-7fd3-b83b-2aaa1b6767f8; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb43-7fd3-b83b-2aba6020504d; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb44-7e13-9d65-d2ac2880bf0a; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb44-7e13-9d65-d2b56d2fd3f2; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb44-7e13-9d65-d2b56d2fd3f2; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb44-7e13-9d65-d2ac2880bf0a; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb45-7a62-8ad3-40fff88d6e1a
2026-02-28 19:52:12,995 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:13,182 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 19:52:13,871 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb45-7a62-8ad3-40fff88d6e1a; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb43-7fd3-b83b-2aba6020504d; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-fb43-7fd3-b83b-2aaa1b6767f8; trace=019ca5ce-faa1-7c21-ad56-19ec151e6ee2,id=019ca5ce-faa1-7c21-ad56-19ec151e6ee2; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01d7-76b3-9385-b4bb7fd78681; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01d8-7be2-b663-93672be44bbc; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01d9-74a3-901d-b1b5350cbd18; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01d9-74a3-901d-b1c3aaab40c6; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01d9-74a3-901d-b1d2283a2584; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01d9-74a3-901d-b1c3aaab40c6; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01d9-74a3-901d-b1d2283a2584; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01dc-7aa0-8135-da88e2f2046c; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01dd-7263-ae4f-21aee565ded8; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01dd-7263-ae4f-21ba3e2e061f; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01dd-7263-ae4f-21aee565ded8; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01dd-7263-ae4f-21ba3e2e061f; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01dc-7aa0-8135-da88e2f2046c; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01d9-74a3-901d-b1b5350cbd18; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01d8-7be2-b663-93672be44bbc; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-0295-70c1-a404-313f74a7b046; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-0296-7a51-9c8c-c8346a3a3944; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-0297-7f70-b8ec-7b696d207ad4; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-0297-7f70-b8ec-7b696d207ad4; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-0296-7a51-9c8c-c8346a3a3944; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-0295-70c1-a404-313f74a7b046; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-029a-7603-826d-3ea8160c8b9f; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-029b-7612-9711-904c01978886; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-029b-7612-9711-9054098fa287; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-029c-7be3-b0da-e38d56a51ec8; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-029c-7be3-b0da-e38d56a51ec8; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-029b-7612-9711-9054098fa287; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-029e-7e02-95f8-3aa46f23a0e3
2026-02-28 19:52:14,392 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:14,576 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 19:52:15,274 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-029e-7e02-95f8-3aa46f23a0e3; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-029b-7612-9711-904c01978886; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-029a-7603-826d-3ea8160c8b9f; trace=019ca5cf-01d7-76b3-9385-b4bb7fd78681,id=019ca5cf-01d7-76b3-9385-b4bb7fd78681; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0740-7b41-9743-e2a099a6e5ce; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0740-7b41-9743-e2ba745c8619; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0740-7b41-9743-e2c59f9ad3b5; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0741-7302-92f0-cd2e52bf64ac; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0741-7302-92f0-cd38ce21326c; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0741-7302-92f0-cd2e52bf64ac; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0741-7302-92f0-cd38ce21326c; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0743-7ae1-b564-f52982d458e9; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0743-7ae1-b564-f53019c900a5; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0743-7ae1-b564-f546e22b044e; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0743-7ae1-b564-f53019c900a5; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0743-7ae1-b564-f546e22b044e; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0743-7ae1-b564-f52982d458e9; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0740-7b41-9743-e2c59f9ad3b5; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0740-7b41-9743-e2ba745c8619; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0806-7412-80c5-7711a82128ba; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0807-7620-8b94-d763e3b8146a; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0807-7620-8b94-d773127119fd; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0807-7620-8b94-d773127119fd; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0807-7620-8b94-d763e3b8146a; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0806-7412-80c5-7711a82128ba; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-080a-7392-b7ed-2a621f75f71b; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-080a-7392-b7ed-2a76774f6956; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-080a-7392-b7ed-2a8521d4ec6c; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-080b-7483-a170-7993bf0bcdeb; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-080b-7483-a170-7993bf0bcdeb; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-080a-7392-b7ed-2a8521d4ec6c; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-080e-7e61-8aab-cce4117b0e21
2026-02-28 19:52:15,371 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:15,541 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 19:52:16,239 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-080e-7e61-8aab-cce4117b0e21; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-080a-7392-b7ed-2a76774f6956; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-080a-7392-b7ed-2a621f75f71b; trace=019ca5cf-0740-7b41-9743-e2a099a6e5ce,id=019ca5cf-0740-7b41-9743-e2a099a6e5ce; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b17-7510-8d8c-0414cc78404e; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b17-7510-8d8c-04222d9442e9; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b17-7510-8d8c-043bae98954a; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b18-7f32-ab53-d8cd8e95a3c8; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b18-7f32-ab53-d8d331d3ac3d; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b18-7f32-ab53-d8cd8e95a3c8; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b18-7f32-ab53-d8d331d3ac3d; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b1b-7823-b432-c5a8a3f5e407; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b1c-7e90-88e7-a89211bf39ef; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b1c-7e90-88e7-a8a011c82000; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b1c-7e90-88e7-a89211bf39ef; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b1c-7e90-88e7-a8a011c82000; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b1b-7823-b432-c5a8a3f5e407; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b17-7510-8d8c-043bae98954a; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b17-7510-8d8c-04222d9442e9; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bce-70b0-aa29-a6e36f0dddac; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bcf-7552-8b5e-f7bdd9ac8201; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bcf-7552-8b5e-f7c02fceba19; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bcf-7552-8b5e-f7c02fceba19; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bcf-7552-8b5e-f7bdd9ac8201; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bce-70b0-aa29-a6e36f0dddac; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bd4-7b50-b68b-baad08a44c9a; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bd4-7b50-b68b-bab599943eda; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bd4-7b50-b68b-bacc6a990c13; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bd5-78e1-8ded-93d09bfdd0af; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bd5-78e1-8ded-93d09bfdd0af; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bd4-7b50-b68b-bacc6a990c13; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bd7-7983-8766-9d8d7ef74b60
2026-02-28 19:52:16,359 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:16,513 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2026-02-28 19:52:17,195 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bd7-7983-8766-9d8d7ef74b60; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bd4-7b50-b68b-bab599943eda; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0bd4-7b50-b68b-baad08a44c9a; trace=019ca5cf-0b17-7510-8d8c-0414cc78404e,id=019ca5cf-0b17-7510-8d8c-0414cc78404e; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef2-7e83-a261-f3c28270a5a8; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef3-7193-89f7-15139808aa0d; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef3-7193-89f7-152ab41c0281; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef3-7193-89f7-153e9e431629; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef4-7ae1-8ff5-072eff0afa05; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef3-7193-89f7-153e9e431629; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef4-7ae1-8ff5-072eff0afa05; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef6-73e2-bad4-15b53e5d590f; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef6-73e2-bad4-15c7e06072fa; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef6-73e2-bad4-15d624fa8c17; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef6-73e2-bad4-15c7e06072fa; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef6-73e2-bad4-15d624fa8c17; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef6-73e2-bad4-15b53e5d590f; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef3-7193-89f7-152ab41c0281; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0ef3-7193-89f7-15139808aa0d; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0f96-7481-9f12-2977549e80e0; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0f96-7481-9f12-2983896de88d; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0f96-7481-9f12-299b1156cae5; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0f96-7481-9f12-299b1156cae5; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0f96-7481-9f12-2983896de88d; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0f96-7481-9f12-2977549e80e0; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0f98-7203-bbe0-e3cd1720eea9; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0f98-7203-bbe0-e3df3d6692f9; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0f98-7203-bbe0-e3efc5ce59b9; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0f98-7203-bbe0-e3f935185b82; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0f98-7203-bbe0-e3f935185b82; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0f98-7203-bbe0-e3efc5ce59b9; trace=019ca5cf-0ef2-7e83-a261-f3c28270a5a8,id=019ca5cf-0f99-7713-922d-722f546b693a
2026-02-28 19:52:17,230 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:17,437 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"

Evaluating:   0%|          | 0/100 [00:00<?, ?it/s]

2026-02-28 19:52:35,406 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca5cf-5146-78f2-ac0f-cb2fc77ebd1b,id=019ca5cf-51ff-7c42-abbe-ebce899fc6e7; trace=019ca5cf-5146-78f2-ac0f-cb2fc77ebd1b,id=019ca5cf-51fd-7dd1-8b82-aa8f7bf93f04; trace=019ca5cf-5146-78f2-ac0f-cb2fc77ebd1b,id=019ca5cf-51fd-7dd1-8b82-aa7717c76a20; trace=019ca5cf-5146-78f2-ac0f-cb2fc77ebd1b,id=019ca5cf-5146-78f2-ac0f-cb2fc77ebd1b; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5684-70f2-ad18-9a0782dbc12f; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5688-7c90-a94b-a7fe04a5fa9a; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5688-7c90-a94b-a806bc8da344; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5689-7f81-a5ef-d4b272d4c815; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5689-7f81-a5ef-d4cf3a612626; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5689-7f81-a5ef-d4de86d58f48; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5689-7f81-a5ef-d4ee4acb81af; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568a-7641-837f-43a630324118; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568b-7011-b409-10dee60f3e77; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568b-7011-b409-10e2a27f8401; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568b-7011-b409-10f7827d3341; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568e-70f3-953b-de5087e47a63; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568e-70f3-953b-de696d1597d4; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568f-7a60-945f-86e324299c26; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568f-7a60-945f-86f87f4ab6cf; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568f-7a60-945f-8702aab4799f; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568f-7a60-945f-8718c9b9cd64; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568f-7a60-945f-872c2655e849; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5690-7233-aac5-33574c7df94d; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5690-7233-aac5-336f9c85f32b; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5690-7233-aac5-337a1f327d9c; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56a5-7e63-b818-b13dfddcbc5e; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56a6-7851-ab2d-3f5ba8eab2b3; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56ad-7ac2-bc9d-27c7ddfef880; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56ad-7ac2-bc9d-27dd7e062b70; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56ae-78b3-a2f0-ec474e7bb553; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56af-7d33-82b2-83c2d6d1b295; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b0-7ac1-8d24-7b7799ebbd6d; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b0-7ac1-8d24-7b81ea74c6b6; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b1-7833-aeaf-283ffc4933fa; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b1-7833-aeaf-284e2ea1cfeb; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b2-78c2-a42e-72fe5739bc47; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b2-78c2-a42e-730ccbd10e45; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b3-7a03-9e58-196f8a6d292b; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b3-7a03-9e58-197bba19366c; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b3-7a03-9e58-19867a75d1d0; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b4-7210-a3fb-3975a6f07ba8; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b4-7210-a3fb-398a264d6104; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b5-7b00-999c-3404b7ea8724; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b5-7b00-999c-3414e3810e9d; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b6-7802-840c-e184d7d59c47; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b6-7802-840c-e198c5de3127; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b6-7802-840c-e1acfa574a64; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b6-7802-840c-e1b1fff1f8b0; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b6-7802-840c-e1c99d6180bd; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b7-76d0-9607-4e1d89fdb095; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b7-76d0-9607-4e248ae12af5; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b7-76d0-9607-4e3dafac0737; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b7-76d0-9607-4e44dbe183b9; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b8-7081-a35d-4b417943edf3; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b8-7081-a35d-4b597539c986; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b8-7081-a35d-4b60d258b328; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56ba-7212-88d3-63a3bf082ef8; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bb-73d3-a10a-db15468f61c5; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bb-73d3-a10a-db264d42d5e1; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bb-73d3-a10a-db36dbac11d5; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bb-73d3-a10a-db42980b12a3; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bb-73d3-a10a-db5f01ae337d; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bb-73d3-a10a-db666b243bcb; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bc-7443-bd67-5c434a7cd277; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bc-7443-bd67-5c5d52208b1f; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bd-7961-ab57-c80cec607ea5; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bd-7961-ab57-c8128da56967; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bf-7081-8526-749f95bb867a; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c0-7bd0-90b1-9ad1a3a559ef; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c1-7d22-bb9f-564bd978914a; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c1-7d22-bb9f-5654574f8435; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c2-7840-8bef-64ff03246e3a; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c2-7840-8bef-6503d474735f; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c2-7840-8bef-651e810bc71c; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c2-7840-8bef-652a1faa44e4; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c3-7dc0-be6b-2b79f6cda237; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c4-7421-8ed3-59b3831f05bf; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c4-7421-8ed3-59c2d431c654; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c4-7421-8ed3-59d2a07fb01f
2026-02-28 19:52:35,613 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:36,137 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:36,139 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:36,140 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:36,141 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:36,142 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:36,142 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:36,143 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:36,144 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:40,096 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:40,098 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:40,101 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:40,104 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:40,106 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:40,107 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:40,108 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:40,109 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:40,118 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:40,119 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:40,120 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:45,551 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:45,553 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:47,219 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b6-7802-840c-e1acfa574a64; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b6-7802-840c-e198c5de3127; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5c25-7c42-b05f-d3617072bfaa; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5c27-7f40-af34-37c9f39fac48; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bb-73d3-a10a-db36dbac11d5; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c2-7840-8bef-6503d474735f; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c4-7421-8ed3-59b3831f05bf; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c2-7840-8bef-652a1faa44e4; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b1-7833-aeaf-283ffc4933fa; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c0-7bd0-90b1-9ad1a3a559ef; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56ad-7ac2-bc9d-27c7ddfef880; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56ba-7212-88d3-63a3bf082ef8; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bb-73d3-a10a-db264d42d5e1; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5e1a-70c2-829b-a91c615aa70d; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5e1d-7c93-a43b-7bb20ce73723; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c2-7840-8bef-64ff03246e3a; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-6019-70b1-b52b-079421319a63; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-601b-7092-97e4-b973373b624a; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c3-7dc0-be6b-2b79f6cda237; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-61fe-71b3-ba0a-643ee9a6d6d6; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-6200-77a3-aee3-00207484339f; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c2-7840-8bef-651e810bc71c; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-63ed-75d1-b036-30cec2ed78aa; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-63ef-7ed0-a402-70771348840f; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b0-7ac1-8d24-7b81ea74c6b6; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-65da-7c90-a239-8412fe5c8eb6; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-65dc-7940-83b4-f1245a8adb2a; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bf-7081-8526-749f95bb867a; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-67b6-75b3-96b1-a9d7b5a782b0; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-67b7-7e92-9340-3cc463da6217; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56a6-7851-ab2d-3f5ba8eab2b3; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-69ad-77a1-a7a3-da59abe19a4a; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-69af-7382-a2db-2795e46780cd; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b8-7081-a35d-4b60d258b328; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b8-7081-a35d-4b597539c986; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-6bad-7921-970d-3717f8265592; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-6bae-7820-94e9-4ac9441c709b; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-6baf-7f81-961a-6af9ff492620; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c4-7421-8ed3-59d2a07fb01f; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b3-7a03-9e58-196f8a6d292b; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b7-76d0-9607-4e248ae12af5; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c1-7d22-bb9f-5654574f8435; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bc-7443-bd67-5c434a7cd277; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b8-7081-a35d-4b417943edf3; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b4-7210-a3fb-3975a6f07ba8; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56af-7d33-82b2-83c2d6d1b295; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bd-7961-ab57-c8128da56967; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b5-7b00-999c-3414e3810e9d; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5c27-7f40-af34-37c9f39fac48; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c4-7421-8ed3-59c2d431c654; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-6da6-7b23-a01a-8739c2b9aad9; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-6da8-75b2-91c3-96873a5f49f7; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b2-78c2-a42e-730ccbd10e45; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-6f8f-78e2-84f9-6e502cccabb9; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-6f91-7c82-a06e-5c88c0b7e863; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b7-76d0-9607-4e1d89fdb095; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-7188-7602-ab4b-ecd2b2d1c466; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-718a-79c0-b453-5e54b476e586; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56c1-7d22-bb9f-564bd978914a; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-7381-7ee2-b380-d3cb168171b5; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-7383-70f2-88d7-0e7c1cd5ab89; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bb-73d3-a10a-db666b243bcb; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-7555-7f53-8197-8d4a21533d15; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-7556-7112-92dd-5f65ba713b3c; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b7-76d0-9607-4e44dbe183b9; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-773e-7ad3-b669-b9c5ad429946; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-773f-7ab3-9790-09ada45df01f; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b3-7a03-9e58-19867a75d1d0; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-7920-76e0-82a1-ecafe3daeeb8; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-7923-78d0-837d-c2f4bf42f14e; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56ae-78b3-a2f0-ec474e7bb553; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56ad-7ac2-bc9d-27dd7e062b70; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-7b0f-7950-97f7-79ed75325663; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-7b0f-7950-97f7-79ffea1296f8; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-7b10-7d73-a412-7d41004e5603; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bd-7961-ab57-c80cec607ea5; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-7cfc-7013-9a16-ac28f8be85fd; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-7cfe-7563-b2e2-d1a734d3487f; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b5-7b00-999c-3404b7ea8724; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b4-7210-a3fb-398a264d6104; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5c25-7c42-b05f-d3617072bfaa; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56b6-7802-840c-e184d7d59c47; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-80f3-72e1-90e2-525383aa4216; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-80f3-72e1-90e2-526332a7166d; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-80f4-7440-b511-629b85d5acfe; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-80f5-7e60-be74-7200d20df113; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-80f7-72b2-b0c8-9ecb4af616de; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-80f8-7742-aef8-91e99d5bd72c; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-80f8-7742-aef8-91f7affdf12d; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-80f9-7e41-9f1a-50bc42de9c4e; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5e1d-7c93-a43b-7bb20ce73723; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-601b-7092-97e4-b973373b624a; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5e1a-70c2-829b-a91c615aa70d; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-56bb-73d3-a10a-db15468f61c5; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-6019-70b1-b52b-079421319a63; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-84d9-7981-b4e1-e35bcd34a8c2; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-84da-74f2-866e-e0f4edf39080; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-84dc-72a0-ad9d-6e9e938aa2d9
2026-02-28 19:52:47,539 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:48,046 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:48,048 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:48,049 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:49,527 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:49,529 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:49,530 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:49,531 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:49,533 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:49,534 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:49,535 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:49,536 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:49,537 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:49,539 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:49,540 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-02-28 19:52:49,540 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

{'context_precision': 0.4853, 'context_recall': 0.9500, 'faithfulness': 0.7922, 'factual_correctness(mode=f1)': 0.6755, 'context_entity_recall': 0.5595}

2026-02-28 19:55:42,677 - WARNING - Failed to send compressed multipart ingest: langsmith.utils.LangSmithRateLimitError: Rate limit exceeded for https://api.smith.langchain.com/runs/multipart. HTTPError('429 Client Error: Too Many Requests for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Too many requests: tenant exceeded usage limits: Monthly unique traces usage limit exceeded"}\n')trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5d2-254c-7181-8241-b6c976ba35ae; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5d2-254a-71c3-aaef-c96acce25236; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5d1-88ca-7bc3-b975-c9adbe8bb4c9; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5d2-2745-7fa1-b5e8-91b0bb78c379; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5d2-2744-70c1-bd35-32a439af49f5; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5d1-67e9-7202-a28d-9d5d991701e1; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5d2-293e-7321-99a2-5c74e1c71ef2; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5d2-293c-7fe0-8a86-5cf9e37c3f11; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5d1-9e5b-7963-9bec-63db38a0a620; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5688-7c90-a94b-a7fe04a5fa9a; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5688-7c90-a94b-a806bc8da344; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5689-7f81-a5ef-d4b272d4c815; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5689-7f81-a5ef-d4cf3a612626; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5689-7f81-a5ef-d4de86d58f48; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5689-7f81-a5ef-d4ee4acb81af; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568a-7641-837f-43a630324118; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568b-7011-b409-10dee60f3e77; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568b-7011-b409-10e2a27f8401; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568b-7011-b409-10f7827d3341; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568e-70f3-953b-de5087e47a63; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568e-70f3-953b-de696d1597d4; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568f-7a60-945f-86e324299c26; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568f-7a60-945f-86f87f4ab6cf; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568f-7a60-945f-8702aab4799f; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568f-7a60-945f-8718c9b9cd64; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-568f-7a60-945f-872c2655e849; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5690-7233-aac5-33574c7df94d; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5690-7233-aac5-336f9c85f32b; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5690-7233-aac5-337a1f327d9c; trace=019ca5cf-5684-70f2-ad18-9a0782dbc12f,id=019ca5cf-5684-70f2-ad18-9a0782dbc12f

In [ ]:
{'context_precision': 0.7167, 'context_recall': 0.8750, 'faithfulness': 0.7461, 'factual_correctness(mode=f1)': 0.5055, 'context_entity_recall': 0.5713}

In [95]:
from pandas import DataFrame

results_df = DataFrame([eval(baseline_synthesia_result.__repr__()), 

eval(hybrid_synthesia_result.__repr__()) ], 
index=['naive_retriever', 
'sparse_and_dense_retriever'])

results_df

,context_precision,context_recall,faithfulness,factual_correctness(mode=f1),context_entity_recall
naive_retriever,0.7167,0.875,0.7461,0.5055,0.5713
sparse_and_dense_retriever,0.4853,0.950,0.7922,0.6755,0.5595

In [ ]:
#test this - this is our actual application
async def search_documents(query: str, case_number) -> str:
    """Search the parsed document chunks for this case using semantic similarity.

    Use this tool to find relevant passages from the documents uploaded for the
    current case (bank statements, annual accounts, etc.).

    Args:
        query: Natural language question or search phrase.
    """
    store = await get_store()
    docs = await store.asimilarity_search(
        query,
        k=5,
        filter={"case_number": case_number},
    )

    if not docs:
        return f"No relevant document chunks found for case '{case_number}'."

    parts = []
    for i, doc in enumerate(docs, 1):
        meta = doc.metadata
        header = (
            f"[Chunk {i} | type={meta.get('chunk_type', '?')} "
            f"| page={meta.get('page_num', '?')}]"
        )
        parts.append(f"{header}\n{doc.page_content}")

    return "\n\n---\n\n".join(parts)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>context_precision</th>
      <th>context_recall</th>
      <th>faithfulness</th>
      <th>factual_correctness(mode=f1)</th>
      <th>context_entity_recall</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>naive_retriever</th>
      <td>0.7167</td>
      <td>0.875</td>
      <td>0.7461</td>
      <td>0.5055</td>
      <td>0.5713</td>
    </tr>
    <tr>
      <th>sparse_and_dense_retriever</th>
      <td>0.4853</td>
      <td>0.950</td>
      <td>0.7922</td>
      <td>0.6755</td>
      <td>0.5595</td>
    </tr>
  </tbody>
</table>
</div>

'|                            |   context_precision |   context_recall |   faithfulness |   factual_correctness(mode=f1) |   context_entity_recall |\n|:---------------------------|--------------------:|-----------------:|---------------:|-------------------------------:|------------------------:|\n| naive_retriever            |              0.7167 |            0.875 |         0.7461 |                         0.5055 |                  0.5713 |\n| sparse_and_dense_retriever |              0.4853 |            0.95  |         0.7922 |                         0.6755 |                  0.5595 |'

Musings on possible improvements

Hybrid search for questions such as dates or assets?